### ISSUE TITLE
README instructions not accurate for me

### ISSUE THREAD

**Issue by gregsandell** [GetStream/Stream-Example-Create-React-App#2]
- I needed to do: `npm i -g node-sass-chokidar`
- The app opens on port 3000, not 8080
- A suggestion for clarifying the purpose of your project.  People may stumble across your project thinking about a kind of streaming other than an activity feed.    For example I want to connect to the output of a running process that is producing unstructured text.  Took me 15 minutes to discover what your project is really about.  I took a look at getstream.io and I see that they also have their own assumption about the meaning of stream, so maybe that's your thinking.  Oh well.

**Comment by dwightgunning** [comment]
Thanks for the feedback and input.

I've added the `node-sass-chokidar` as a project dependency (rather than relying on it being installed globally) and adjusted the readme based on your suggestions.
